name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'appName'
    value: 'react-reference-app'

jobs:
  - template: javascript/react-complete-build.yml@templates
    parameters:
      appName: '$(appName)'
