name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'prod-bip/ssb/dapla/react-reference-app'

jobs:
  - job: testApplicationAndAnalyzeCode
    displayName: 'Run test and coverage reporting'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    steps:
      - script: |
          yarn install
          CI=true yarn coverage
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'bipSonarQube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: '$(SONAR_TOKEN)'
          cliSources: '.'
      - task: SonarQubeAnalyze@4
  - job: buildAndPushDocker
    displayName: 'Build and push Docker image'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    steps:
      - script: |
          yarn install
          CI=true yarn build
      - task: Docker@2
        displayName: 'Login to GCR'
        inputs:
          command: login
          containerRegistry: gcrServiceConnection
      - task: Docker@2
        inputs:
          containerRegistry: 'gcrServiceConnection'
          repository: '$(imageName)'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: '$(Build.SourceBranchName)-imagescan-$(fullSha)'
