name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: 'refs/heads/feature/docker-remote-retag'
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: 'appName'
    value: 'react-reference-app'
  - name: 'imageTag'
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)'

jobs:
  - template: javascript/react-complete-build-test.yml@templates
    parameters:
      appName: $(appName)
      imageTag: $(imageTag)
